name: SelfCorrect
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.6
  - pip:
    - torch==2.6.0
    - transformers==4.49.0
    - accelerate==1.5.2
    - hydra-core
    - datasets
    - litellm
    - protobuf
    - tiktoken
    - blobfile
    - SentencePiece
    - flash_attn
